license = "PDDL-1.0"
keywords = [ "Education", "Literature", "Censorship"]
created_at = "2016-09-13"
updated_at = "2016-09-13"
period = [1979, 2015]
frequency = "monthly"
category= "Education"
author = "Small Media Foundation"

name = "writersblock"

[[title]]
lang = "en"
text = "Dataset of books from Iran Book House"

[[title]]
lang = "fa"
text = "Dataset of books from Iran Book House"

[[description]]
lang = "fa"
text = "Over 880,000 books extracted from the Iran Book House website. The Iran Book House maintains a database of all the published books that get sent to the National Library."

[[description]]
lang = "en"
text = "Over 880,000 books extracted from the Iran Book House website. The Iran Book House maintains a database of all the published books that get sent to the National Library."


[[resources]]

  url = "http://example.com/csv"
  name = "writersblock-data"

  [[resources.title]]
  lang = "en"
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "Iran Book House"
  web = "http://ketab.ir"

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Author"
      type = "string"

      [[resources.schema.fields]]
      name = "Publisher"
      type = "string"

      [[resources.schema.fields]]
      name = "Title"
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "date"
